### PR TITLE
fix(ISSUE-810): oneOf/allOf/anyOf fixing

### PR DESCRIPTION
**Pull request by sadfsdfdsa**
Issue: https://github.com/drwpow/openapi-typescript/issues/810

**Type: FIX**
**Tests: 100%**
**Affects: oneOf/allOf/anyOf**

Now doesn't crash while parse the empty oneOf/allOf/anyOf type, for dummy placeholder uses `undefined` for all empty `xOf` types:

image
image

### CODE REVIEW

**Comment by drwpow** [comment]
Same as the other PR—this will need to be rebased, but overall I’m in favor of it! I’d love to approve & merge once tests are passing.

**Comment by sadfsdfdsa** [comment]
@drwpow rdy to be merged

**Comment by deannashih** [comment]
@sadfsdfdsa Sorry, just saw your comments from https://github.com/drwpow/openapi-typescript/issues/810. I think `undefined` is fine! Better than my having to manually remove the fields with the empty `*Of`s altogether. Let me know when I can update my app to use these changes. Thanks a bunch!

**Comment by drwpow** [comment]
@all-contributors please add @sadfsdfdsa for bug

**Comment by drwpow** [comment]
Released in `5.1.0`! 🎉

**Comment by sadfsdfdsa** [comment]
@deannashih released in `5.1.0`

**Pull request merged**
