### PR TITLE
Fix type discrimination for non-overlapping content types

### LINKED ISSUE #1609: Type discrimination between `data` and `error` doesn't work
**Description**

A simple if-statement on `dataRes.data` fails to correctly discriminate `data` and `error`, which results in the `error` type being `never`:

```ts
const dataRes = await GET('/');

if (dataRes.data) {
  expectTypeOf(dataRes.data).toEqualTypeOf({
    objects: [{ id: '', name: '' }],
  });
} else {
  expectTypeOf(dataRes.data).toBeUndefined();
  expectTypeOf(dataRes.error).toEqualTypeOf({ errors: { body: [''] } });
}
```

<details><summary>The OpenAPI spec used for this example</summary>

```yaml
openapi: 3.0.1
info:
  title: Test API
  version: 1.0.0
  
paths:
  /:
    get:
      description: List objects
      operationId: GetObjects
      responses:
        '200':
          $ref: '#/components/responses/ObjectsResponse'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '422':
          $ref: '#/components/responses/GenericError'

components:
  schemas:
    Object:
      required:
        - id
        - name
      type: object
      properties:
        id:
          type: string
        name:
          type: string
    GenericErrorModel:
      required:
        - errors
      type: object
      properties:
        errors:
          required:
            - body
          type: object
          properties:
            body:
              type: array
              items:
                type: string
  responses:
    ObjectsResponse:
      description: Objects
      content:
        application/json:
          schema:
            required:
              - objects
            type: object
            properties:
              objects:
                type: array
                items:
                  $ref: '#/components/schemas/Object'
    Unauthorized:
      description: Unauthorized
      content: {}
    GenericError:
      description: Unexpected error
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/GenericErrorModel'
```

</details>

**Reproduction**

https://stackblitz.com/edit/vitejs-vite-vnadlg?file=README.md&view=editor

**Expected result**

It should allow checking `dataRes.data` or `dataRes.error` and choosing either the success type or the error type

**Checklist**

- [x] I’m willing to open a PR (see [CONTRIBUTING.md](https://github.com/drwpow/openapi-typescript/blob/main/packages/openapi-fetch/CONTRIBUTING.md))

### PR DESCRIPTION
**Pull request by illright**
## Changes

Fixes #1609 

## How to Review

I've added a new kind of test — Vitest type test, to verify the correctness of this solution.

## Checklist

- [x] Unit tests updated
- [ ] `docs/` updated (if necessary)
- [ ] `pnpm run update:examples` run (only applicable for openapi-typescript)

### CODE REVIEW

**Comment by drwpow** [comment]
This is great, thank you!

If you could fix the linting error, and add a `patch` changeset (see comment), I’d be happy to merge. The tests pass locally for me; there seems to be an issue in CI right now that’s unrelated to your PR.

**Review by drwpow — APPROVED** [review]

**Comment by JrSchild** [comment]
Hi @illright. Does this also fix the issue where both data and result can not infer correctly to their respective types after an if check?

```
const dataRes = await GET('/');

// data is never
if (dataRes.data !== undefined) console.log(dataRes.data);
```

**Comment by illright** [comment]
@JrSchild hard to say, I would need to see your openapi schema as well. Feel free to check out this branch and try it out for yourself

**Comment by illright** [comment]
@drwpow is it ready to go?

**Comment by drwpow** [comment]
Ah thanks for the poke! Looks great and will merge; CI tests are currently experiencing an issue that I’ll fix this week.

**Comment by drwpow** [comment]
Released in the latest version of `openapi-fetch`. Thanks again!

**Pull request merged**
