### PR TITLE
Use lowercase headers

### PR DESCRIPTION
**Pull request by HiiiiD**
## Changes
_What does this PR change? Link to any related issue(s)._

Undici returns headers in lowercase as it can be seen [here](https://github.com/nodejs/undici/blob/a3ce745b0c5d7c837ecae2359434ab4550a6e0ea/lib/core/util.js#L214). This PR updates the `content-type` check in order to use the lowercase version.

## How to Review

_How can a reviewer review your changes? What should be kept in mind for this review?_

## Checklist

- [ ] Unit tests updated
- [ ] README updated
- [ ] `examples/` directory updated (if applicable)

### CODE REVIEW

**Comment by timothymctim** [comment]
This would fix an issue for me: my backend server sends the `Content-Type` header in lower case. Since key indices in JavaScript are case sensitive, this would fix it for me, but this fix would break the code for others as it wouldn’t match `Content-Type` any more. The following code would normalize the header key first before selecting and using it.
```
let contentType = res.headers[Object.keys(res.headers).find(key => key.toLowerCase() === 'content-type')]
contentType = Array.isArray(contentType)
    ? contentType[0]
    : contentType;
```

**Comment by HiiiiD** [comment]
As I said in the first PR comment, Undici returns all headers in lowercase, so that's not an issue @timothymctim

**Comment by timothymctim** [comment]
> As I said in the first PR comment, Undici returns all headers in lowercase, so that's not an issue @timothymctim

Indeed, that the case! Sorry, my bad :)

**Review by drwpow — APPROVED** [review]

**Comment by drwpow** [comment]
@all-contributors please add @HiiiiD for code, test

**Pull request merged**
