### PR TITLE
schema input from stdin

### PR DESCRIPTION
**Pull request by kgtkr**
fix: #869

### CODE REVIEW

**Review by drwpow — CHANGES_REQUESTED** [review]
Thank you! I’m in favor of this change and would like to see this merged. However, before we do, could you please add a test to `cli.test.js`?

There is a test for `stdout` already; please add one there for `stdin` so we can be sure there are no regressions with this in the future.

**Comment by kgtkr** [comment]
@drwpow
Thank you for your review. I added a test.

**Comment by Richard87** [comment]
I would love this feature as well! I saw the readline-sync library on npmjs.org with 760'000 weekly downloads, but the logic seemed pretty complicated to get right in all environments, maybe pull in that library if you want stdin support for windows (and powershell +++) instead of managing it yourself? 

https://www.npmjs.com/package/readline-sync
https://github.com/anseki/readline-sync/blob/master/lib/readline-sync.js

**Comment by kgtkr** [comment]
Sorry I'm late. I was able to fix it.
But in CI, `pnpm install` fails in one place. I think it will be sucuceed if you re-execute.

**Comment by drwpow** [comment]
Thanks for fixing! 🙏 Re-running the test now to see if it’s just flaky (and will fix in a followup)

**Review by drwpow — APPROVED** [review]

**Pull request merged**
