### PR TITLE
fix: properties + anyOf with only required properties

### LINKED ISSUE #642: Empty `Partial<{ [key: string]: any }>` in case of `schema.anyOf` with only `required` keys
I think the best will be to just filter out `anyOf` items that only have `required` keys. I'll try a PR to explore the effect of such a change for further discussion, ok?

This is currently causing TypeScript problems in @octokit, see https://github.com/octokit/types.ts/issues/319#issuecomment-856305469

### PR DESCRIPTION
**Pull request by gr2m**
fixes #642

### CODE REVIEW

**Comment by gr2m** [comment]
looks like the `14.x` CI fails due to some weird caching of a previous `prettier` version?

**Comment by gr2m** [comment]
I've published `@gr2m/openapi-typescript@4.0.0-fork.2` and use it in @octokit for the time being, feel free to give a try if you have the same problem

**Comment by drwpow** [comment]
> looks like the `14.x` CI fails due to some weird caching of a previous `prettier` version?
> 
> image

Hm. Maybe try rebasing off latest `main` and repushing? Maybe that will clear the cache

**Comment by drwpow** [comment]
Actually I can try that real quick myself; forgot that you have access and this was a local branch in the project 🙂

**Comment by gr2m** [comment]
doesn't look like it helped? Super odd, I don't know what's up sorry :(

**Comment by drwpow** [comment]
Oh I figured it out—the snapshots were just updated with an older local version of Prettier. No big deal—easy fix. No code changes necessary.

**Review by drwpow — APPROVED** [review]

**Comment by gr2m** [comment]
> the snapshots were just updated with an older local version of Prettier

🤦🏼 sorry for that

**Comment by gr2m** [comment]
> the snapshots were just updated with an older local version of Prettier

🤦🏼 sorry for that

**Pull request merged**
