### PR TITLE
fix(schema-object): transform toplevel schema object

### LINKED ISSUE #1619: Transform only transforms referenced schemas
**Description**

I'm using a small script with a transform function like in the [example](https://openapi-ts.pages.dev/node#example-blob-types) to transform schemas of `type: string, format: binary` to `Blob`s. However this only happens when it is within a schema that is referenced, not when I specify the schema in place.

| Name                 | Version                      |
| :------------------- | :--------------------------- |
| `openapi-typescript` | `^7.0.0-next.8` |
| Node.js              | `21.7.1`                      |
| OS + version         | `nixos unstable (24.05)` |

**Reproduction**

I have created this simple spec.yml, which has one post route with the schema defined in place and one with the schema in a reference.

```yml
openapi: "3.0.0"
info:
  version: 1.0.0
  title: Schema issue
  license:
    name: MIT
    url: https://opensource.org/license/mit
servers:
  - url: something.com
paths:
  /api/file-no-schema:
    post:
      security: []
      summary: "no schema"
      operationId: noSchema
      requestBody:
        content:
          application/json:
            schema:
              type: string
              format: binary
      responses:
        200:
          description: "s3 url of the uploaded image"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/FileReturn"
        400:
          description: "bad request"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        default:
          description: "unknown error"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
  /api/file-with-schema:
    post:
      security: []
      summary: "with schema"
      operationId: withSchema
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/File"
      responses:
        200:
          description: "s3 url of the uploaded image"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/FileReturn"
        400:
          description: "bad request"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        default:
          description: "unknown error"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
components:
  schemas:
    File:
      type: string
      format: binary
    FileReturn:
      properties:
        s3Url:
          type: string
    Error:
      required:
        - code
        - message
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string
```

and I'm transforming it with this script:

```mjs
import fs from "node:fs";
import openapiTS, { astToString } from "openapi-typescript";
import ts from "typescript";

const BLOB = ts.factory.createIdentifier("Blob"); // `Blob`
const NULL = ts.factory.createLiteralTypeNode(ts.factory.createNull()); // `null`

let openapiPath = "../spec.yml";

console.log(`⌛Loading openapi schema from ${openapiPath}`);
console.log("✨Transforming binary data to file");
const ast = await openapiTS(new URL(openapiPath, import.meta.url), {
  transform(schemaObject, metadata) {
    if (schemaObject.format === "binary") {
      return schemaObject.nullable
        ? ts.factory.createUnionTypeNode([BLOB, NULL])
        : BLOB;
    }
  },
});

let contents = `/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

`;

contents += astToString(ast);

let path = "./generated/v1.d.ts";

console.log(`🖊️Writing schema to ${path}`);
fs.writeFileSync(path, contents);
```

**Expected result**

I'd expect the request Body of the `noSchema` endpoint:

```ts
...
        requestBody?: {
            content: {
                "application/json": string;
            };
        };
...
```

to not be of type `string`, but of type `Blob`, just like the generated type of the `File` schema:

```ts
...
    schemas: {
        /** Format: binary */
        File: Blob;
...
```

**Checklist**

- [x] My OpenAPI schema passes the [Redocly validator](https://redocly.com/docs/cli/commands/lint/) (`npx @redocly/cli@latest lint`)
- [x] I’m willing to open a PR (see [CONTRIBUTING.md](https://github.com/drwpow/openapi-typescript/blob/main/packages/openapi-typescript/CONTRIBUTING.md))

### PR DESCRIPTION
**Pull request by LucaSchwan**
## Changes

Closes #1619

## How to Review

I'm not sure if this is the right place to call the transform yet. So please give me some feedback on wether it is ok there or if it should go somewhere else. I've 

## Checklist

- [x] Unit tests updated
- [x] `docs/` updated (if necessary)
- [x] `pnpm run update:examples` run (only applicable for openapi-typescript)

### CODE REVIEW

**Comment by drwpow** [comment]
Thanks so much! At a glance this seems correct, but if you could rebase from the latest `main` (`git fetch && git rebase origin/main`) this may still have some errors before we can verify if this is the correct solution. But it looks like it’s on the right track either way!

**Comment by LucaSchwan** [comment]
I rebased, there was some error in the ci before, I'll look into that when the workflow ran again on the rebased code.

**Comment by LucaSchwan** [comment]
I just had the API of the `TransformObject` wrong. But I fixed it.

**Review by drwpow — APPROVED** [review]
This is great, thank you!

**Pull request merged**
