### PR TITLE
Support for making references to schema properties

### PR DESCRIPTION
**Pull request by Peteck**
Fixes issue #617

### CODE REVIEW

**Comment by drwpow** [comment]
Cool. This looks great, but I wouldn’t want to merge this without adding a test first. Can you write a unit test for this?

I think a great place would be in `schema.test.ts`, there is a `$ref` and `$ref (external)` test; maybe this could be a `$ref (properties)` test? Just in one place should be enough to make sure this is working as intended.

**Comment by drwpow** [comment]
Actually, on second thought, now that #602 is merged, we can keep your approach, but we’ll have to move it to [load.ts#L152](https://github.com/drwpow/openapi-typescript/blob/main/src/load.ts#L152). Something like:

```diff
  let [base, ...rest] = parts;
+ if (rest[rest.length - 2] === 'properties') rest.splice(rest.length - 2, 1); // if "properties" is next-to-last segment, remove
  return `${base}["${rest.join('"]["')}"]`;
```

The change was due to the fact that because we resolve remote schemas, we have to resolve `$ref`s at the very beginning in order to figure out what to load. And we have to transform them at the very beginning, too, because we only have that context during resolution. But other than that, this should look familiar to your approach here; it just moved to a different spot in the codebase.

**Comment by Peteck** [comment]
> Cool. This looks great, but I wouldn’t want to merge this without adding a test first. Can you write a unit test for this?

Sure

> Actually, on second thought, now that #602 is merged, we can keep your approach, but we’ll have to move it to [load.ts#L152](https://github.com/drwpow/openapi-typescript/blob/main/src/load.ts#L152).

All right, I will move it :slightly_smiling_face:

**Comment by drwpow** [comment]
Just checking in. Are you still able to make this change? Then we can get this merged.

Sorry again for the v4 disruption on this!

**Review by drwpow — APPROVED** [review]
Approved pending moving to `load.ts` (as this utility no longer exists)

**Comment by Peteck** [comment]
I chose to make the test as a schema-load-test in v2 and v3. That is because the check and change is made at the load phase, and the test in `schema.test.ts` is not for tests in the loading phase.

**Comment by drwpow** [comment]
> I chose to make the test as a schema-load-test in v2 and v3. That is because the check and change is made at the load phase, and the test in `schema.test.ts` is not for tests in the loading phase.
> 
> And sorry about the late response, I've been busy 🙂

No worries at all! I totally understand—I only work on this project when I have time as well. 🙂

**Comment by avaly** [comment]
Is there anything blocking merging this PR?

I also ran into this issue recently and would like to get this patch available.

**Comment by drwpow** [comment]
> Is there anything else blocking merging this PR?
> 
> I also ran into this issue recently and would like to get this patch available.

Nope! Sorry—I fell a little behind on maintenance for this project and am just now catching up. Will publish this in the next release!

**Comment by drwpow** [comment]
@all-contributors please add @Peteck for code, bug

**Pull request merged**
