### PR TITLE
make status codes numeric

### LINKED ISSUE #380: Numeric status codes
Hello, I really like this library but I had to fork it to be able to actually use it.

My issue is that the `responses` object lists the response status codes as strings. I need to be able to use numeric values in my codebase and I am not able to check them against the generated TS types.

---

My solution was to replace the `{ [statusCode]: responseBodies }` object with a discriminated union:

```ts
responses:
  | { statusCode: 200, bodies: … }
  | { statusCode: 202, bodies: … }
  | { statusCode: 400, bodies: … }
```

I can get a numeric enum from that simply by using `responses['statusCode']`.

---

I've also noticed that TS allows actual numeric keys such as `{ 200: … }` (instead of `{ "200": … }`) so that could be enough.

Would such a change be acceptable? What is the actual reason the keys are strings anyway?

### PR DESCRIPTION
**Pull request by jankuca**
Closes #380

### CODE REVIEW

**Review by gr2m — COMMENTED** [review]
great PR! @drwpow if you agree with the change, I think we should release this as a breaking change.

I'll test the change against my own work with @octokit to see if I run into any trouble, as I ran into the same problem you did

**Review by gr2m — APPROVED** [review]
This changes works well for my usage in @octokit. Accessing the responses works the same using `...["responses"]["200"]`. The only difference is that `keyof paths["..."]["get"]["responses"]` returns `200 | 404` instead of `"200" | "404"`

I say let's go ahead with it. I'm not even sure if I would consider the change a breaking change, but when in doubt I'd always rather go with a breaking change.

**Review by drwpow — APPROVED** [review]

**Comment by drwpow** [comment]
> I'm not even sure if I would consider the change a breaking change, but when in doubt I'd always rather go with a breaking change.

Yeah I could go either way here. I think it technically is a breaking change, but it’s a breaking change on a newly-released feature. I agree with erring on the side of breaking change, and cutting `3.0` for this

**Comment by drwpow** [comment]
@all-contributors please add @jankuca for code, test

**Comment by drwpow** [comment]
OK I tagged @ released `3.0.0-rc.0` with these changes. If y’all have time to test the changes that’d be great! Overall I feel pretty confident in it, but just in case wanted to just kick the tires a bit before releasing `3.0.0`.

**Pull request merged**
