### PR TITLE
feat: add `--x-nullable-as-nullable` to treat schemas with `x-nullable` as being able to specify `null`

### PR DESCRIPTION
**Pull request by mitchell-merry**
## Changes

Essentially adds the `nullable` feature from 3.0 into 2.0 as well, behind the `--x-nullable-as-nullable` flag.

## How to Review

Stacked on https://github.com/drwpow/openapi-typescript/pull/1575!

## Checklist

- [x] Unit tests updated
Specifically didn't add too much so as not to over-test. This is not a commonly used version, anywho

### CODE REVIEW

**Comment by drwpow** [comment]
Thanks for adding this! I’m good with this addition. While I know 3.x encourages `type: [null]` as the recommended way, `nullable: true` and `x-nullable: true` are still really common patterns I see in 3.x schemas and I think supporting both doesn’t stand in the way of the 3.x specs while providing value to users. +1 to this landing.

**Comment by mitchell-merry** [comment]
Specifically, this is to support a 2.x schema, where I believe there is no official pattern for nullable (outside of this `x-nullable` thing) (which is why I am PRing into 5.x 😄).

**Review by drwpow — APPROVED** [review]

**Comment by mitchell-merry** [comment]
Thanks for the merge! Could we get a release of 5.x with this change?

**Comment by drwpow** [comment]
Published!

**Pull request merged**
