### PR TITLE
Fix breaking JSDoc changes (#1012)

### LINKED ISSUE #1012: JsDoc breaking changes from 5-6
Using version 6.1.0 
1. The jsdoc comments for operations is generated above the first child of the operation in document order. This means the comment intended for the operation may end up parameters/responses/etc depending on which child is defined first.
2. All parameter descriptions are mashed together as @description tags above "path" instead of being rendered above the corresponding parameter

Example:
``` ts
export interface operations {

  getVisits: {
    /** swagger description value from getVisits INCORRECTLY renders here */
    parameters: {
      /** 
            @description The numeric store Id (this should be above storeId)
            @description The store name (this should be above storeName)
      */
      path: {
        storeId: number;
        storeName: number;
      };
    };
    responses: {
      /** @description Success */
      200: {
        content: {
          "application/json": (components["schemas"]["SchedulerVisitReadModel"])[];
        };
      };
    };
  };
```

### PR DESCRIPTION
**Pull request by mitchell-merry**
## Changes
Fixes #1012

- Parameters correctly generate next to the intended parameter (this was a typo I believe)
- Operation comments now generate above the operation instead of inside (in this case there was also a duplicate comment generated when the operation had no operationId)

The example linked in the issue now generates as:
```ts
export type operations = {

  /** getVisits description (now attached to getVisits) */
  getVisits: {
    parameters: {
      path: {
        /** @description storeId description (now correctly on the property) */
        storeId: string;
        /** @description storeName description */
        storeName: string;
      };
    };
    responses: {
      /** @description Success */
      200: {
        content: {
          "application/json": components["schemas"]["SchedulerVisitReadModel"];
        };
      };
    };
  };
};
```

## How to Review

The tests were wrong in this instance, so they have been updated as well.

## Checklist

- [x] Unit tests updated
- [x] `examples/` directory updated (if applicable)

### CODE REVIEW

**Comment by mitchell-merry** [comment]
Hi @drwpow, just wondering what's blocking you from merging some of these PRs? I'd like to work on additional features but I'm hesitant since it seems like this project has stagnated.

**Review by drwpow — APPROVED** [review]
This is a great fix, and great tests. Thank you!

**Comment by drwpow** [comment]
> Hi @drwpow, just wondering what's blocking you from merging some of these PRs?

I contribute as much time to the project as I can, which is several hours every month. I’d love help with additional maintainers if you’re interested or know someone who is.

**Comment by mitchell-merry** [comment]
> This is a great fix, and great tests. Thank you! Will merge as soon as the lint errors & minor conflicts are resolved.

Thanks! Could you rerun the workflow? I'm getting `Response is not a constructor` errors on my local (for load.test.ts) for both my branch and main, so I want to make sure that it works in CI (no idea what my issue is on local).

> I contribute as much time to the project as I can, which is several hours every month. I’d love help with additional maintainers if you’re interested or know someone who is.

That's good to hear. I want to start using this package, so I'm hoping that it's still being at least somewhat maintained. As long as I can submit PRs and there's someone around to check them, that's good by me :D thanks for what you do.

**Pull request merged**
