### PR TITLE
feat: `requestBody`, `$ref`-type parameters

### LINKED ISSUE #329: Support `$ref`-type parameters, as well as components.parameters
Followup from #236.

We don’t yet support the following schema:

```yaml
paths:
  '/some/path':
    get:
      parameters:
        - "$ref": "#/components/parameters/since"
        - "$ref": "#/components/parameters/per_page"
        - "$ref": "#/components/parameters/page"
```

Add support for `$ref` parameters as well as add the `components.parameters` object to the final response.

There’s an existing spec which illustrates this: `tests/v3/specs/github.yaml`.

### LINKED ISSUE #333: set empty response type to `never`
If a response has no content key, e.g. 

```json
"responses": {
  "204": {
    "description": "Empty response"
  }
}
```

The resulting type is currently `any`: 

```ts
responses: {
  /**
   * Empty response
   */
  "204": any;
};
```

But I'd argue the better type would be `never`

### LINKED ISSUE #338: requestBody parameters are missing
For example, GitHub's example schema (`tests/v3/specs/github.yaml`) has lots of `requestBody` parameters. But the generated TypeScript types (`tests/v3/expected/github.ts`) do not have any of it

As suggested in my comment here: https://github.com/drwpow/openapi-typescript/issues/236#issuecomment-701054647, I'd transform something like this

```yml
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                description:
                  type: string
                homepage:
                  type: string
                private:
                  type: boolean
                  default: false
              required:
                - name
```

into

```ts
      requestBody: {
        "application/json": {
          name: string;
          description?: string;
          homepage?: string;
          private?: boolean;
        };
      };
```

### PR DESCRIPTION
**Pull request by gr2m**
This PR combines the other separate PRs I opened. If you want to merge them all, merging this one is the easiest way, as there are some merge conflicts

closes #337 
closes #339

fixes #329
fixes #338

### CODE REVIEW

**Review by drwpow — APPROVED** [review]
Already approved the other ones; happy to merge this one or the others. Your pick! (also, sorry—I probably should have started with this one!)

**Comment by gr2m** [comment]
no worries, I should have warned you :D I'll probably resolve the conflicts and address https://github.com/drwpow/openapi-typescript/pull/337#discussion_r511181303 in this PR, so I don't have to resolve the conflicts twice for #337 and #339

**Comment by gr2m** [comment]
ready for you @drwpow

**Comment by gr2m** [comment]
oh how exciting, thank you!! Could you release a new version? I'd be also happy to help you setup semantic-release for continuous releases via GitHub Actions, so you will never see a question like this again lol

**Comment by drwpow** [comment]
Of course! I can release a new minor version with these awesome new features.

Re: semantic-release, I’m pretty neutral on it. Autoreleases are awesome, but in your experience has it been difficult trying to get commit messages to be formatted properly? Happy to do whatever is less work overall.

**Comment by gr2m** [comment]
I'm not really impartial because I'm one of the maintainers of `semantic-release` :D There are really only 3 conventions that matter, I would document them in `CONTRIBUTING.md`, such as https://github.com/octokit/rest.js/blob/master/CONTRIBUTING.md#merging-the-pull-request--releasing-a-new-version

The biggest boo boo that I've seen happening is when someone had a typo in `BREAKING CHANGE:` and semantic-release published a fix/feature release instead of a breaking one. But that's fixed easy enough, I'd be here to help with all your semantic-release questions anyway.

But I do say this: I would never be able to maintain as many npm packages as I do without semantic-release. No way.

**Comment by drwpow** [comment]
OK you’ve sold me! 🙂 I’ll try adding it myself, and ping you if I have any questions.

**Pull request merged**
