### PR TITLE
Translate openapi-typescript for Chinese

### PR DESCRIPTION
**Pull request by phk422**
## Changes

Complete 'openapi-typescript' documentation in Chinese

### CODE REVIEW

**Comment by phk422** [comment]
Hi @drwpow ! If possible, I would also like to appear on the list of contributors. If it's not convenient, I don't mind. I will work on completing other pages in my spare time!

**Comment by drwpow** [comment]
> Hi @drwpow ! If possible, I would also like to appear on the list of contributors. If it's not convenient, I don't mind. I will work on completing other pages in my spare time!

You absolutely will go on the list of contributors! Anyone that has merged any PR for anything goes on that list. Just add your name to `docs/scripts/add-contributors.js` and the automation does the rest. Thanks so much for all you’ve done!

**Review by drwpow — APPROVED** [review]

**Comment by drwpow** [comment]
Just invited you to be a collaborator on this project so you can merge this whenever you’d like. You’ll be able to open up PRs yourself, but will just need a ✅ from me

**Comment by phk422** [comment]
> Just invited you to be a collaborator on this project so you can merge this whenever you’d like. You’ll be able to open up PRs yourself, but will just need a ✅ from me

I finished the translation and merged it, and if there are subsequent updates, I am happy to support them in my free time.

**Comment by drwpow** [comment]
You work so quickly, thank you for the amazing work! 🙌 This opens the door to so many more devs, and I love to see it ❤️

**Pull request merged**
